# Generated by Django 5.0.4 on 2024-05-02 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_image', models.ImageField(null=True, upload_to='imagess')),
            ],
        ),
        migrations.CreateModel(
            name='Productmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_image', models.ImageField(null=True, upload_to='imagess')),
                ('product_description', models.TextField(null=True)),
                ('product_price', models.IntegerField()),
                ('product_stock', models.IntegerField()),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.categorymodel')),
            ],
        ),
    ]
